
image: ubuntu:17.04
before_script:
    - apt-get update
    - curl -sLO https://bootstrap.pypa.io/get-pip.py

build:
    stage: build
    script:
        - apt-get install -y python3.6
        - python3.6 setup.py sdist
    artifacts:
        paths:
        - dist/

python3-test:
    script:
        - apt-get install -y python3.6
        - python3.6 get-pip.py
        - rm get-pip.py
        - pip install --no-index file://dist/*
        - ls `python -c "import chromedriver_binary; print(chromedriver_binary.chromedriver_filename)"`
    dependencies:
    - build

python2-test:
    script:
        - apt-get install -y python2.7
        - python2.7 get-pip.py
        - rm get-pip.py
        - pip install --no-index file://dist/*
        - ls `python -c "import chromedriver_binary; print(chromedriver_binary.chromedriver_filename)"`
    dependencies:
    - build
